import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Berkshire_Swash } from "next/font/google";
import "./globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const berkshire = Berkshire_Swash({
  variable: "--font-berkshire",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Root Beverages",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${berkshire.variable}`}>
      <body>{children}</body>
    </html>
  );
}
